version: '3'
services:
  sender:
    build:
      context: ./sender
    depends_on:
      - receiver1
      - receiver2
      - receiver3
      - proxy
    ports:
      - "8081:8080"
  receiver1:
    build:
      context: ./receiver
    depends_on:
      - heartbeat
    ports:
      - "8082:8080"
    environment:
      - CONTAINER_NAME=receiver1
  receiver2:
    build:
      context: ./receiver
    depends_on:
      - heartbeat
    ports:
      - "8083:8080"
    environment:
      - CONTAINER_NAME=receiver2
  receiver3:
    build:
      context: ./receiver
    depends_on:
      - heartbeat
    ports:
      - "8084:8080"
    environment:
      - CONTAINER_NAME=receiver3
  proxy:
    build:
      context: ./proxy
    depends_on:
      - heartbeat
      - receiver1
      - receiver2
      - receiver3
    ports:
      - "8087:8080"
    environment:
      - CONTAINER_NAME=proxy
  heartbeat:
    build:
      context: ./heartbeat
    ports:
      - "8085:8080"